CREATE TABLE IF NOT EXISTS Post (
    id TEXT PRIMARY KEY CHECK(LENGTH(id) = 36),
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    visibility TEXT NOT NULL CHECK(visibility IN ('PUBLIC', 'PRIVATE')),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Post (id, title, created_at, description, visibility) VALUES 
('08abea3e-240f-454e-aaa4-379900c4f605', 'File Storage Impl: Part 1', '2023-12-21 18:14:39.24497+00', '', 'PRIVATE'), 
('15642b10-1759-44c1-bf90-be91720d699d', 'Personal Website Update', '2023-03-28 17:14:27.029971+00', 'The portfolio website has been updated, and this note explains the changes. The previous version of the website only contained notes. However, after the recent update, I decided to add a front page and a project page, and I updated the layout of the notes. In addition, I adjusted the responsiveness to better fit mobile users (not entirely satisfied with the outcome, but it works).', 'PUBLIC'),
('3f9e8f5f-263f-48d1-897b-2db50ea64561', 'Kubernetes Zero to Hero: Part 3', '2023-04-29 20:04:22.147121+00', 'This series of notes is about my experience learning and configuring a Kubernetes cluster. Previously, I used a single Virtual Machine to host all my web applications. However, they have become cumbersome to keep track of and are hard to deploy and update. In addition, cloud technologies are in trend and something I want to get practical and theoretical experience on. This article will explain my improvements from the last post, adding a <strong>Proxy</strong> and implementing <strong>Grafana</strong> for monitoring.', 'PUBLIC'), 
('6c92de12-a2b2-4e14-bd3b-372f8a51a8aa', 'File Storage: Part 1', '2023-12-25 17:40:22.200891+00', 'Improved TLS versions ensure secure data transport from client to server without extra client-side encryption. In this note, I&#39;&#39;ll explain how to add unnecessary encryption when uploading files in the Phoenix web framework. In the rare case, a zero-day is discovered in the TLS protocol, causing data to leak. Adding an additional layer of encryption and integrity could be the solution. This note will explain how I set up client-side encryption and server-side decryption using <a href="https://github.com/digitalbazaar/forge">forge.js</a>, <a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API">the Web Crypto API</a> and Erlang&#39;&#39;s <a href="https://www.erlang.org/doc/man/crypto">:crypto</a> and <a href="https://www.erlang.org/doc/man/public_key">:public_key</a> libraries <strong>NB!</strong> This solution increases the overhead of uploading files and is only an example. I do not recommend it for direct production usage. It is not Post-Quantum safe either, but a Post-Quantum Hybrid Key Exchange may be future work.', 'PUBLIC'), 
('74d59295-0c03-4516-ba0b-fa414d5f0b56', 'Dependency setup for Kubeadm', '2023-02-05 15:30:46.069503+00', 'The setup consists of 3 EC2 instances of type t3.small (2 vCPU and 2 GiB Memory) running on Ubuntu 22.10. The following script was executed on each node to successfully initialize/join the Kubernetes cluster.', 'PRIVATE'), 
('7d123de4-fb70-4ba0-9cca-f69c84c7a216', 'Kubernetes Zero to Hero: Part 1', '2023-02-05 22:16:47.141236+00', 'This series of notes is about my experience learning and configuring a Kubernetes cluster. Previously, I used a single Virtual Machine to host all my web applications. However, they have become cumbersome to keep track of and are hard to deploy and update. In addition, cloud technologies are in trend and something I want to get practical and theoretical experience on.', 'PUBLIC'), 
('b86ff89d-a28d-4b7a-8436-782dcc25dfe3', 'Project Updates June 2023 - March 2024', '2024-03-23 15:49:37.45901+00', 'This note outlines updates from last year until March 2024 in bullet-point format for the following three projects: the proxy server, Kubernetes cluster, and portfolio application. The proxy server and Kubernetes cluster received updates that enhanced security, performance, and manageability. Meanwhile, the portfolio application underwent improvements related to the user experience.', 'PUBLIC'), 
('bd3226ba-5b3e-427d-8815-a3350402f510', 'File Storage: Part 1', '2023-03-14 14:20:45.149874+00', 'This note reflects my framework selection of the current in-development application: File Storage. As an Elixir enthusiast, I selected Phoenix for both the front- and backend. I have had superb experience using the framework for backend APIs and WebSocket. After the recent 1.7 release, the CSS framework Tailwind was added to LiveView, which I have previously used and found beneficial. Therefore I  also decided to use it on the frontend. It provides predefined classes that can be used to style inline, streamlining the development process and eliminating the need for CSS files. Furthermore, one of the new key features of Phoenix that caught my attention is its built-in support for streaming large files efficiently. Given that the File Storage application will likely involve handling large amounts of data, this capability is crucial for delivering a smooth and responsive user experience.', 'PRIVATE'), 
('ce163d0f-5c3c-4cca-9788-16871429b6b8', 'RaspberryPI eBook Library', '2023-09-15 17:38:06.532471+00', 'These notes were written after I configured my first RaspberryPI. It is a RaspberryPI 4 Model B with 8GB RAM, a 64-bit processor, and a 32 GB SD card. The main goal was to host a self-hosted library web application only accessible to me.', 'PUBLIC'), 
('dc034859-46bf-4d8c-8736-ad5b3c201021', 'Kubernetes Zero to Hero: Part 2', '2023-02-24 19:34:31.185772+00', 'This series of notes is about my experience learning and configuring a Kubernetes cluster. Previously, I used a single Virtual Machine to host all my web applications. However, they have become cumbersome to keep track of and are hard to deploy and update. In addition, cloud technologies are in trend and something I want to get practical and theoretical experience on. This article will explain the infrastructure and setup to deploy my chess and simple chat applications. ', 'PUBLIC');
