#ifndef WIND_BREAKER_VERSION_H
#define WIND_BREAKER_VERSION_H

#define WIND_BREAKER_VERSION_MAJOR 1
#define WIND_BREAKER_VERSION_MINOR 1
#define WIND_BREAKER_VERSION_PATCH 1

#define WIND_BREAKER_VERSION "1.1.1"

#endif // MYAPP_VERSION_H
