name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc \
            make \
            libssl-dev \
            zlib1g-dev \

      - name: Create build directory
        run: mkdir -p build

      - name: Configure the project
        run: cmake -S . -B build

      - name: Build the project
        run: cmake --build build

      - name: Run unit tests
        run: ./build/unit_test

      - name: Generate self-signed certificate
        run: | 
          mkdir -p /etc/wind_breaker
          openssl req -x509 -newkey rsa:4096 -keyout /etc/wind_breaker/key.pem -out /etc/wind_breaker/cert.pem -sha256 -days 365 -nodes -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost"

      - name: Run simulations
        run: |
          touch /tmp/logs
          (./build/main &> /tmp/logs) & echo "MAIN_PID=$!" >> $GITHUB_ENV
          sleep 5
          ./build/client

      - name: Print logs
        if: always()
        run: cat /tmp/logs

      - name: Stop server
        run: kill $MAIN_PID
